### ISSUE TITLE
Provide image with `lvm2` & different filesystems (`ext4`, `xfs`) aside of `btrfs`

### ISSUE THREAD

**Issue by GamePlayer-8** [cwt-vf2/archlinux-image-vf2#15]
Hello,

Would there be an option to provide the rootfs inside of `lvm2` and with different file systems like `ext4` or `xfs`?

**Comment by cwt** [comment]
I use Btrfs on my image for several reasons:

1. I'm a strong advocate for Btrfs.
2. In my opinion, Btrfs with compression and async discard is the optimal filesystem for NAND flash media (e.g., microSD cards, eMMC, and NVMe SSDs) - all of which are available options on the VisionFive 2.
3. I can experiment with different distributions by simply editing `extlinux.conf` and adding new entries to mount `root` on different `subvolumes`. For example, I can boot into Fedora by extracting the Fedora rootfs into an `@fedora` subvolume and changing the kernel parameter to `subvol=@fedora`.

However, if you prefer a different storage configuration, you can clone and modify [my script](https://github.com/cwt-vf2/archlinux-image-vf2/blob/main/build.sh) to create an alternative image that better suits your needs. I encourage you to do so.

**Comment by GamePlayer-8** [comment]
Will edit your script.

I've asked for different filesystems due to the corruption of `btrfs` filesystem on SDCards. While `btrfs` might be a good choice on NVMe, eMMC or SSDs, it might not work that well on unstable storage mediums.

**Comment by cwt** [comment]
@GamePlayer-8 I agree, Btrfs required a stable flash media.
