### ISSUE TITLE
reporting cwt18 archlinux boots successfully

### ISSUE THREAD

**Issue by omac777** [cwt-vf2/archlinux-image-vf2#3]
Here is what I did:

### write vf2 debian minimal desktop to sdcard

```
sudo bash
lsblk
 ### umount anypartitions on /dev/sda
wipefs --all /dev/sda
bunzip2 starfive-jh7110-VF2_515_v3.8.2-66-SD-minimal-desktop-wayland.img.bz2
dd bs=4M if=starfive-jh7110-VF2_515_v3.8.2-66-SD-minimal-desktop-wayland.img of=/dev/sda status=progress
#don't forget to resize its root partition to take advantage of any free sdcard capacity
gparted /dev/sda
```

### boot into vf2 debian minimal desktop to flash the latest spl and the uboot

```
apt-get install mtd-utils
cat /proc/mtd
### dev: size erasesize name
### mtd0: 00040000 00001000 "spl"   <<<----blasting this one
### mtd1: 00010000 00001000 "uboot-env"
### mtd2: 00300000 00001000 "uboot"    <<<<----blasting this one
### mtd3: 00100000 00001000 "data"
flashcp -v u-boot-spl.bin.normal.out /dev/mtd0
flashcp -v visionfive2_fw_payload.img /dev/mtd2
sync
sync
shutdown -h now
```

### write cwt18 vf2 archlinux minimal image to sdcard

```
lsblk
umount /run/media/cissy/root 
wipefs --all /dev/sda
xzcat ./ArchLinux-VF2_5.15.2_v3.8.2-cwt18.img.xz | sudo dd bs=4M conv=fsync of=/dev/sda

#don't forget to resize its root partition to take advantage of any free sdcard capacity
gparted /dev/sda
```

I inserted the cwt18 archlinux sdcard into the vf2.
- cwt18 archlinux reboots correctly. 
- cwt18 archlinux shuts down correctly as well.
- displays clinfo successfully

**Comment by omac777** [comment]
I have some questions:
- what desktop have you attempted to install with archlinux?
- with cwt18 archlinux, may we `pacman -Syuu` now?

**Comment by cwt** [comment]
@omac777 Thanks for your report. I don’t use GUI or desktop on my VF2, I use it headlessly most of the time. However, there are many people who try to use GUI on this image, such as Gnome, KDE, Wayfire, as you can see in this [thread](https://forum.rvspace.org/t/mesa-kde-plasma-on-archlinux/3711) . I occasionally use wayland/weston to test the GUI capability. If you want to talk to people who trying to make this image become a fully desktop, join us on https://matrix.to/#/#archlinux-riscv:matrix.org

**Comment by cwt** [comment]
>     * with cwt18 archlinux, may we `pacman -Syuu` now?

I'm always run that command first thing in the morning. :-)

**Comment by omac777** [comment]
cwt, please never forget you're a superhero!
