### ISSUE TITLE
Boot from sd card and ssh into it?

### ISSUE THREAD

**Issue by Kreijstal** [cwt-vf2/archlinux-image-vf2#6]
I can boot from Debian 69 from sd card, but I can't access through ssh when booting from sd card or actually it doesn't seem to automatically get an ip address I'm trying this with cwt20.img

**Comment by cwt** [comment]
If I understand correctly, you're asking that can you ssh to the board with cwt20?

Yes, this image has sshd enabled by default. Once you boot the VF2 with cwt20, you needed to login on the board first, either with attached monitor and keyboard or the serial console, then check the IP address that you got from your DHCP.

**Comment by Kreijstal** [comment]
> If I understand correctly, you're asking that can you ssh to the board with cwt20?
> 
> Yes, this image has sshd enabled by default. Once you boot the VF2 with cwt20, you needed to login on the board first, either with attached monitor and keyboard or the serial console, then check the IP address that you got from your DHCP.

Oh, I just use the router to tell me the address, do you need to log in from com or insider does it not boot into a state that I can simply ssh into it with just sd card (no [NVMe](https://www.digitaltrends.com/computing/nvme-vs-ssd/) nor eMMC, just sd/tf card, ethernet CAT-6 cable and usb-c cable for power?)

**Comment by cwt** [comment]
That is right, just SD card and power supply, if you can get IP address from your router.

Check this [link](https://forum.rvspace.org/t/arch-linux-image-for-visionfive-2/1459) for more details.
